services:
  app:
    profiles: ["prod"]
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    image: yp-online-showcase
    container_name: "yp-online-showcase"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/postgres
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    profiles: ["prod"]
    image: postgres:15-alpine
    container_name: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    image: test-image
    container_name: "test-container"
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: test
      # DB config
      SPRING_DATASOURCE_URL: r2dbc:postgresql://test-db:5432/test_db
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      DB_NAME: test_db
      DB_HOST: test-db
      DB_PORT: 5432
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      - test-db

  test-db:
    container_name: "test-db"
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_db"]
      interval: 5s
      timeout: 10s
      retries: 20
    volumes:
      - test_db_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  test_db_data: